name = "fortran"
version = "0.1.0"
license = "license"
author = "Christopher Albert"
maintainer = "albert@tugraz.at"
copyright = "Copyright 2025, Christopher Albert"
description = "Make Python Fortran again - Run Fortran programs directly without manual compilation"
[build]
auto-executables = true
auto-tests = true
auto-examples = false
module-naming = false
[install]
library = false
test = false
[dependencies]
fpm = { git = "https://github.com/krystophny/fpm.git" }
json-fortran = { git = "https://github.com/jacobwilliams/json-fortran.git" }

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[extra.ford]
project = "fortran"
src_dir = ["src", "app"]
output_dir = "build/doc"
exclude_dir = ["build", "test"]
page_dir = "doc"
project_github = "https://github.com/krystophny/fortran"
project_download = "https://github.com/krystophny/fortran/releases"
project_website = "https://krystophny.github.io/fortran/"
display = ["public", "protected"]
source = true
graph = true
search = true
[extra.ford.extra_mods]
iso_fortran_env = "https://gcc.gnu.org/onlinedocs/gfortran/ISO_005fFORTRAN_005fENV.html"

