name = "fortran"
version = "0.1.0"
license = "license"
author = "Christopher Albert"
maintainer = "albert@tugraz.at"
copyright = "Copyright 2025, Christopher Albert"
[build]
auto-executables = true
auto-tests = true
auto-examples = false
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

